#!/bin/sh

usr() {
    echo "Rebuilding user configuration..."
    # uname -a | grep NixOS && echo "You are not on NixOs, aliasing home-manager to use flakes" && \
    #     alias home-manager="home-manager --extra-experimental-features nix-command"

    home-manager switch --flake ".#$user"
}

sys() {
    echo "Rebuilding system configuration..."
    echo "As this is multi-user, you will be prompted for a password."
    sudo nixos-rebuild switch --flake ".#$host" $args
}

case $1 in 
    "desktop") user="fears" && host="steambox"
    ;;
    "laptop") user="fears" && host="hazed"
    ;;
    "asahi") user="focus" && host="steamfunk" && args="--impure"
    ;;
    *) echo "Enter a host to rebuild: desktop, laptop, or asahi" && exit 1
    ;;
esac

case $2 in
    "usr") usr 
    ;;
    "sys") sys
    ;;
    "all") sys && usr
    ;;
    *) echo "Enter a target to rebuild: usr or sys" && exit 1
    ;;
esac

