#!/bin/sh

usr() {
    echo "Rebuilding user configuration..."
    home-manager switch --flake ".#$user"
}

sys() {
    [ -z $host ] && echo "This set up doesnt suport a system build" && exit 1

    echo "Rebuilding system configuration..."
    echo "As this is multi-user, you will be prompted for a password."
    sudo nixos-rebuild switch --flake ".#$host"
}

case $1 in 
    "desktop") user="fears" && host="steambox"
    ;;
    "laptop") user="fears" && host="hazed"
    ;;
    "asahi") user="focus"
    ;;
    *) echo "Enter a host to rebuild: desktop, laptop, or asahi" && exit 1
    ;;
esac

case $2 in
    "usr") usr 
    ;;
    "sys") sys
    ;;
    "all") sys && usr
    ;;
    *) echo "Enter a target to rebuild: usr or sys" && exit 1
    ;;
esac

